name: CI pipeline for YouthBranch UI

on:
  push:
    branches:
      - staging

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cloudflared
        run: |
          wget -O cloudflared https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-amd64
          chmod +x cloudflared
          sudo mv cloudflared /usr/local/bin/cloudflared

      - name: Add SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup SSH config
        run: |
          mkdir -p ~/.ssh
          echo "Host ssh-windows-server
            HostName ssh-windows-server.aiotlab.edu.vn
            ProxyCommand cloudflared access ssh --hostname %h
            User Administrator
            Port 22
          " > ~/.ssh/config
          chmod 600 ~/.ssh/config

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Zip build folder
        run: zip -r dist.zip dist

      - name: Copy build to server via SCP
        run: scp -o StrictHostKeyChecking=no dist.zip ssh-windows-server:C:/Users/Administrator/

      - name: Deploy to IIS via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ssh-windows-server powershell -Command "
            \$ErrorActionPreference = 'Stop';
            \$siteName = 'YouthBranch';
            \$target = 'C:\inetpub\wwwroot\$siteName';
            Stop-Website -Name \$siteName;
            Remove-Item '\$target\*' -Recurse -Force -ErrorAction SilentlyContinue;
            Expand-Archive -Path 'C:\Users\Administrator\dist.zip' -DestinationPath \$target -Force;
            Start-Website -Name \$siteName;
            Remove-Item 'C:\Users\Administrator\dist.zip' -Force
          "