name: CI pipeline for YouthBranch UI

on:
  push:
    branches:
      - staging

jobs:
  build:
    runs-on: [self-hosted, windows]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Deploy to IIS
        run: |
          $ErrorActionPreference = "Stop"
          $siteName = "YouthBranch"
          $target = "C:\inetpub\wwwroot\$siteName"
          Stop-Website -Name $siteName
          Remove-Item "$target\*" -Recurse -Force -ErrorAction SilentlyContinue
          Copy-Item ".\dist\*" -Destination $target -Recurse -Force
          Start-Website -Name $siteName
        shell: powershell